// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using colaboracaoapi.Infra;

#nullable disable

namespace colaboracaoapi.Migrations
{
    [DbContext(typeof(ColaboracaoContext))]
    partial class ColaboracaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("colaboracaoapi.Models.Colaboracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumColaboradores")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Colaboracoes");
                });

            modelBuilder.Entity("colaboracaoapi.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ColaboracaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColaboracaoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("colaboracaoapi.Models.Usuario", b =>
                {
                    b.HasOne("colaboracaoapi.Models.Colaboracao", "Colaboracao")
                        .WithMany("Usuarios")
                        .HasForeignKey("ColaboracaoId");

                    b.Navigation("Colaboracao");
                });

            modelBuilder.Entity("colaboracaoapi.Models.Colaboracao", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
